import { z } from 'zod'

export const createPrescriptionSchema = z.object({
  encounterId: z.string().min(1),
  items: z.array(z.object({
    name: z.string().min(1),
    dose: z.string().optional(),
    frequency: z.string().optional(),
    duration: z.string().optional(),
    notes: z.string().optional(),
  })).min(1),
  labTests: z.array(z.string().min(1)).optional(),
  labNotes: z.string().optional(),
  diagnosticTests: z.array(z.string().min(1)).optional(),
  diagnosticNotes: z.string().optional(),
  primaryComplaint: z.string().optional(),
  primaryComplaintHistory: z.string().optional(),
  familyHistory: z.string().optional(),
  treatmentHistory: z.string().optional(),
  allergyHistory: z.string().optional(),
  history: z.string().optional(),
  examFindings: z.string().optional(),
  diagnosis: z.string().optional(),
  advice: z.string().optional(),
  vitals: z.object({
    pulse: z.coerce.number().optional(),
    temperatureC: z.coerce.number().optional(),
    bloodPressureSys: z.coerce.number().optional(),
    bloodPressureDia: z.coerce.number().optional(),
    respiratoryRate: z.coerce.number().optional(),
    bloodSugar: z.coerce.number().optional(),
    weightKg: z.coerce.number().optional(),
    heightCm: z.coerce.number().optional(),
    bmi: z.coerce.number().optional(),
    bsa: z.coerce.number().optional(),
    spo2: z.coerce.number().optional(),
  }).partial().optional(),
  createdBy: z.string().optional(),
})

export const updatePrescriptionSchema = z.object({
  items: z.array(z.object({
    name: z.string().min(1),
    dose: z.string().optional(),
    frequency: z.string().optional(),
    duration: z.string().optional(),
    notes: z.string().optional(),
  })).min(1).optional(),
  labTests: z.array(z.string().min(1)).optional(),
  labNotes: z.string().optional(),
  diagnosticTests: z.array(z.string().min(1)).optional(),
  diagnosticNotes: z.string().optional(),
  primaryComplaint: z.string().optional(),
  primaryComplaintHistory: z.string().optional(),
  familyHistory: z.string().optional(),
  treatmentHistory: z.string().optional(),
  allergyHistory: z.string().optional(),
  history: z.string().optional(),
  examFindings: z.string().optional(),
  diagnosis: z.string().optional(),
  advice: z.string().optional(),
  vitals: z.object({
    pulse: z.coerce.number().optional(),
    temperatureC: z.coerce.number().optional(),
    bloodPressureSys: z.coerce.number().optional(),
    bloodPressureDia: z.coerce.number().optional(),
    respiratoryRate: z.coerce.number().optional(),
    bloodSugar: z.coerce.number().optional(),
    weightKg: z.coerce.number().optional(),
    heightCm: z.coerce.number().optional(),
    bmi: z.coerce.number().optional(),
    bsa: z.coerce.number().optional(),
    spo2: z.coerce.number().optional(),
  }).partial().optional(),
})
